<?php
require  __DIR__ . "/layout/header.php";
?>
<section class="register">
    <div class="container">
        <form method="post">
            <div class="form-item">
                <label for="">Почта</label>
                <input value="<?= $body['email'] ?? '' ?>" name="email" type="text">
                <span><?= $errors['email'] ?? '' ?></span>
            </div>
            <div class="form-item">
                <label for="">Пароль</label>
                <input value="<?= $body['password'] ?? '' ?>" name="password" type="text">
                <span><?= $errors['password'] ?? '' ?></span>
            </div>
            <span><?= $authError ?? '' ?></span>
            <button>Отправить</button>
        </form>
    </div>
</section>

</body>
</html>