<?php
require  __DIR__ . "/layout/header.php";
?>

<section class="forum">
    <div class="container">
        <div class="forum-inner">
            <?php if(isset($_COOKIE['token'])): ?>
            <a href="/record">Создать запись</a>
            <?php endif; ?>
            <div class="forum-sidebar">
                <form>
                    <h4>Ключевые слова</h4>
                    <input value="<?= $_GET['name'] ?? ''  ?>" name="name" type="text">

                    <h4>Теги</h4>
                    <ul class="tag-list">
                        <?php foreach ($tags as $tag): ?>
                        <li class="tag-item">
                            <label for="tag<?= $tag['id'] ?>"><?= $tag['name'] ?></label>
                            <input
                                <?php if(isset($_GET['tag']) && in_array($tag['id'], $_GET['tag']) ): ?>
                                    checked
                                <?php endif; ?>
                                id="tag<?= $tag['id'] ?>"
                                value="<?= $tag['id'] ?>" name="tag[]" type="checkbox">
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <button>Отправить</button>
                </form>
            </div>
            <div class="forum-content">
                <?php foreach ($records as $record): ?>
                <div class="forum-item">
                    <h2>
                        <a href="/forum/<?= $record['id'] ?>"><?= $record['name'] ?></a>
                        <p><?= $record['text'] ?></p>
                    </h2>
                </div>
                <?php endforeach; ?>

                <?php
                $queryNext = '';
                $queryPref = '';

                if(empty($_SERVER['QUERY_STRING'])){
                    $_SERVER['QUERY_STRING'] = http_build_query(['page' => 2]);
                    $queryNext = http_build_query(['page' => 2]);
                    $queryPref = http_build_query(['page' => 1]);
                }else{
                    $query = [];
                    parse_str($_SERVER['QUERY_STRING'], $query);

                    $query['page'] = isset($query['page']) ? $query['page'] + 1 : 2;
                    $queryNext = http_build_query($query);

                    $query['page'] = max(1, $query['page'] - 2); ;
                    $queryPref = http_build_query($query);
                }

                $url = $_SERVER['REQUEST_URI'];
                $url = explode('?', $url);
                $url = $url[0];

                ?>
                <a href="<?= $url ?>?<?= $queryPref ?>">Предыдущая страница</a>
                <a href="<?= $url ?>?<?= $queryNext ?>">Следующая страница</a>
            </div>
        </div>
    </div>
</section>
