<?php
require  __DIR__ . "/layout/header.php";
?>

<section class="forum">
    <div class="container">
        <div class="forum-inner">
            <?php if(isset($_COOKIE['token'])): ?>
            <a href="/record">Создать запись</a>
            <?php endif; ?>
            <div class="forum-sidebar">
                <form>
                    <h4>Ключевые слова</h4>
                    <input value="<?= $_GET['name'] ?? ''  ?>" name="name" type="text">

                    <h4>Теги</h4>
                    <ul class="tag-list">
                        <?php foreach ($tags as $tag): ?>
                        <li class="tag-item">
                            <label for="tag<?= $tag['id'] ?>"><?= $tag['name'] ?></label>
                            <input
                                <?php if(isset($_GET['tag']) && in_array($tag['id'], $_GET['tag']) ): ?>
                                    checked
                                <?php endif; ?>
                                id="tag<?= $tag['id'] ?>"
                                value="<?= $tag['id'] ?>" name="tag[]" type="checkbox">
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <button>Отправить</button>
                </form>
            </div>
            <div class="forum-content">
                <?php foreach ($records as $record): ?>
                <div class="forum-item">
                    <h2>
                        <a href="/forum/<?= $record['id'] ?>"><?= $record['name'] ?></a>
                        <p><?= $record['text'] ?></p>
                    </h2>
                </div>
                <?php endforeach; ?>

                <?php

                $url = $_SERVER['REQUEST_URI'];
                $url = explode('?', $url);
                $url = $url[0];

                ?>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <?php for ($i = 1; $i <= $pages; $i++): ?>
                        <?php
                            $isActive = false;
                            if(isset($_GET['page']) && $_GET['page'] == $i){
                                $isActive = true;
                            }
                            if(empty($_GET['page']) && $i == 1){
                                $isActive = true;
                            }
                            ?>
                        <li class="page-item">
                            <a class="page-link <?= $isActive ? 'active' : '' ?>"
                               href="<?= $url ?>?<?= http_build_query(array_merge($_GET, ['page' => $i])) ?>"><?= $i ?></a>
                        </li>
                        <?php endfor; ?>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
