<?php
require  __DIR__ . "/layout/header.php";
?>
    <section class="profile">
        <div class="container">
            <div class="profile-inner">
                <h2>Профиль пользователя</h2>

                    <form enctype="multipart/form-data" method="post">
                        <label>Загрузить новое фото</label>
                        <input name="photo" accept="image/png, image/gif, image/jpeg" type="file">
                        <button>Загрузить фото</button>
                    </form>
                <?php if(isset($user['photo'])): ?>
                    <div>
                        <span>Ваше фото</span>
                        <img src="/<?= $user['photo'] ?>" alt="">
                    </div>
                <?php endif; ?>
                <h4>Логин пользователя: <?= $user['login'] ?></h4>
                <h4>Почта пользователя: <?= $user['email'] ?></h4>
                <h4>Дата создания аккаунта: <?= $user['created_at'] ?></h4>
            </div>
        </div>
    </section>
</body>
</html>