<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <section class="register">
        <div class="container">
            <form method="post">
                <div class="form-item">
                    <label for="">Логин</label>
                    <input value="<?= $body['login'] ?? '' ?>" name="login" type="text">
                    <span><?= $errors['login'] ?? '' ?></span>
                </div>
                <div class="form-item">
                    <label for="">Почта</label>
                    <input value="<?= $body['email'] ?? '' ?>" name="email" type="text">
                    <span><?= $errors['email'] ?? '' ?></span>
                </div>
                <div class="form-item">
                    <label for="">Пароль</label>
                    <input value="<?= $body['password'] ?? '' ?>" name="password" type="text">
                    <span><?= $errors['password'] ?? '' ?></span>
                </div>
                <div class="form-item">
                    <label for="">Повторите пароль</label>
                    <input value="<?= $body['confirm_password'] ?? '' ?>" name="confirm_password" type="text">
                    <span><?= $errors['confirm_password'] ?? '' ?></span>
                </div>
                <span><?= $registerError ?? '' ?></span>
                <button>Отправить</button>
            </form>
        </div>
    </section>

</body>
</html>