<?php
require  __DIR__ . "/layout/header.php";
?>
    <section class="register">
        <div class="container">
            <form method="post">
                <div class="form-item">
                    <label for="">Логин</label>
                    <input value="<?= $body['login'] ?? '' ?>" name="login" type="text">
                    <span><?= $errors['login'] ?? '' ?></span>
                </div>
                <div class="form-item">
                    <label for="">Почта</label>
                    <input value="<?= $body['email'] ?? '' ?>" name="email" type="text">
                    <span><?= $errors['email'] ?? '' ?></span>
                </div>
                <div class="form-item">
                    <label for="">Пароль</label>
                    <input value="<?= $body['password'] ?? '' ?>" name="password" type="text">
                    <span><?= $errors['password'] ?? '' ?></span>
                </div>
                <div class="form-item">
                    <label for="">Повторите пароль</label>
                    <input value="<?= $body['confirm_password'] ?? '' ?>" name="confirm_password" type="text">
                    <span><?= $errors['confirm_password'] ?? '' ?></span>
                </div>
                <span><?= $registerError ?? '' ?></span>
                <button>Отправить</button>
            </form>
        </div>
    </section>

</body>
</html>